<a href="https://colab.research.google.com/github/SUMIT74184/Machine-learning-journey/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello I'm excited to learn pytorch")

hello I'm excited to learn pytorch


## Pytorch Fundamentals

In [ ]:
!nvidia-smi

Fri Dec 12 07:53:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.9.0+cpu


In [ ]:
#Tensors
#scalar
scalar=torch.tensor(7)


In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
Matrix=torch.tensor([[1,2]
                     ,[9,8]])
Matrix

tensor([[1, 2],
        [9, 8]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[0]

tensor([1, 2])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR=torch.tensor([[[1,2,3]
                      ,[4,5,6]
                      ,[6,7,8]
                      ,[9,8,17]]])

In [ ]:
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 6,  7,  8],
         [ 9,  8, 17]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8],
        [ 9,  8, 17]])

# Random Tensors
* Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

* start with random numbers -> look at data -> update random numbers -> look at the data -> update random numbers

In [ ]:
# Create the random tensors of shape (3,4)
random_tensor=torch.rand(5,4)
random_tensor

tensor([[0.5466, 0.8680, 0.4817, 0.6809],
        [0.3995, 0.8668, 0.0101, 0.2414],
        [0.7522, 0.5811, 0.8463, 0.7406],
        [0.5060, 0.3896, 0.3349, 0.7980],
        [0.1907, 0.0399, 0.9701, 0.0088]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channesl(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(size=(1,3,3))

tensor([[[0.6695, 0.4983, 0.0984],
         [0.4234, 0.6399, 0.1097],
         [0.7065, 0.0972, 0.2626]]])

#Zeros and Ones


In [ ]:
# Create a tensor of all zeros
zeros=torch.zeros(size=(4,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Creating a Range of tensors and tensor-like

In [ ]:
### use torch.arange(start,end,stop)
one_to_range=torch.arange(start=0,end=1000,step=50)
one_to_range

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [ ]:
one_to_ranges=torch.arange(start=0,end=225,step=15)
one_to_ranges

tensor([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180, 195,
        210])

In [ ]:
# Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes
**Note:** Tensort datatypes is one of 3 big errors you'll run into with pytorch & deep learning:

 1.Tensor not right datatype

 2.Tensor not right shape

 3.Tensor not on the right device

In [ ]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.4,3.1,2.1],
                             dtype=None,
                             device=None, # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3.4000, 3.1000, 2.1000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_newTensor=torch.tensor([2.0,2.1,2.2],
                                dtype=None,
                                device=None,
                                requires_grad=False
                                )
float_16_newTensor

tensor([2.0000, 2.1000, 2.2000])

In [ ]:
float_16_newTensor*float_32_tensor

tensor([6.8000, 6.5100, 4.6200])

In [ ]:
#converted the 32 to 16 datatype for the float
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.4004, 3.0996, 2.0996], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([11.5613,  9.6088,  4.4092])

In [ ]:
# Creating with int32 and long
# int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor=torch.tensor([3,6,9]
                           ,dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([10.2000, 18.6000, 18.9000])

### Getting information from tensors (Tensor Attributes)

1.Tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`

2.Tensor not right shape - to get shape from a tensor , can use `tensor.shape`

3.Tensor not on the right device -  to get device from a tensor, can use `tensor.device`

In [ ]:
# create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0030, 0.9873, 0.9154, 0.7196],
        [0.8711, 0.8739, 0.3661, 0.8133],
        [0.4922, 0.4141, 0.9538, 0.2151]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Size of tensor:{some_tensor.size()}")
print(f"Device tensor is on:{some_tensor.device}")
print(f"Shape of tensor:{some_tensor.shape}")


tensor([[0.0030, 0.9873, 0.9154, 0.7196],
        [0.8711, 0.8739, 0.3661, 0.8133],
        [0.4922, 0.4141, 0.9538, 0.2151]])
Datatype of tensor:torch.float32
Size of tensor:torch.Size([3, 4])
Device tensor is on:cpu
Shape of tensor:torch.Size([3, 4])


# Manipulating Tensors (tensor operation)

Tensor operation include:

Add,Sub,Multiply,Division

Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,4])
tensor+10

tensor([11, 12, 14])

In [ ]:
tensor*10

tensor([10, 20, 40])

In [ ]:
tensor/10

tensor([0.1000, 0.2000, 0.4000])

In [ ]:
nmtens=torch.tensor([-9,-3,-4])

In [ ]:
nmtens*10

tensor([-90, -30, -40])

In [ ]:
torch.mul(nmtens,100)

tensor([-900, -300, -400])

In [ ]:
torch.add(nmtens,20)

tensor([11, 17, 16])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks

1.Element-wise multiplication

2.Matrix multipication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

  1.The **inner dimensions** must match:

    * `(3,2) @ (3,2)` won't work
    * `(2,3) @ (3,2)` will work
    * `(3,2) @ (2,3)` will work
  
  2. The resulting matrix has the shape of the **outer dimensions**:
    
    * `(2,3) @ (3,2)` -> (2,2)
    * `(3,2) @ (2,3)` -> (3,3)


In [29]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2))  mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2679, 0.9991, 0.2750],
        [0.2351, 0.5853, 0.2568],
        [0.3485, 1.2256, 0.3616]])

In [30]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7656, 1.0396],
        [1.0475, 1.0853]])

In [31]:
#randomly defining the matrix
torch.matmul(torch.rand(3,1),torch.rand(1,3))

tensor([[0.1692, 0.5413, 0.2671],
        [0.1609, 0.5148, 0.2540],
        [0.1811, 0.5792, 0.2858]])

In [ ]:
#Element wise multiplication
tensor*tensor
print(tensor ,"*", tensor)

tensor([1, 2, 4]) * tensor([1, 2, 4])


In [ ]:
print(f"Equals:{tensor*tensor}")

Equals:tensor([ 1,  4, 16])


In [ ]:
#Matrix Multiplication-->
torch.matmul(tensor,tensor)

tensor(21)

In [ ]:
#Matrix multipication manual way
1*1 + 2*2 + 4*4

21

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(21)
CPU times: user 1.08 ms, sys: 1 ms, total: 2.08 ms
Wall time: 2.41 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 424 µs, sys: 0 ns, total: 424 µs
Wall time: 338 µs


tensor(21)

# Matrix multiplication dealing with tensor shape Errors

In [34]:
# shape for matrix multiplication
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,11]])
torch.mm(tensor_A,tensor_B)



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [35]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

A **transpose** switches the axes or dimensions of a given tensors

In [40]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 11]])

In [38]:
tensor_B.T.shape

torch.Size([2, 3])

In [37]:
#original tensor_B
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 11]])

In [41]:
tensor_B.shape

torch.Size([3, 2])

In [45]:
torch.matmul(tensor_B.T,tensor_B)

tensor([[194, 257],
        [257, 342]])

In [43]:
torch.matmul(tensor_B,tensor_B.T)

tensor([[149, 166, 173],
        [166, 185, 193],
        [173, 193, 202]])

In [48]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A= {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape} <-inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape: {output.shape}")


Original shapes: tensor_A= torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <-inner dimensions must match
Output:

tensor([[ 27,  30,  31],
        [ 61,  68,  71],
        [ 95, 106, 111]])

output shape: torch.Size([3, 3])


# Find min,max,sum,mean,etc (tensor aggregation)


In [63]:
#Create a tensor
x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [66]:
#find the mean
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
#find the mean --> function requires a tensor of float32 datatypes
torch.mean(x.type(torch.float32))


tensor(45.)

In [60]:
x.type(torch.float32).mean()

tensor(45.)

In [62]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [74]:
x+1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [76]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum values occur
x.argmin()

tensor(0)

In [77]:
x.argmax()

tensor(9)

## Reshaping,stacking,squeezing and unsequeezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted(Swapped) in certain way

In [100]:
import torch
x=torch.arange(1.,11.)

In [101]:
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [102]:
# Add an extra dimension
x_reshaped=x.reshape(10,1)
x_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [130]:
x_reshaped=x.reshape(1,10)
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [131]:
# Change the view
z=x.view(1,10)
z,z.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [132]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [140]:
# stacks tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [134]:
# torch.squeeze()
print(f"Previous tensor{x_reshaped}")
print(f"Previos shape{x_reshaped.shape}")

#remove extra dimensions from x_reshaped

x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"\nNew Shape:{x_squeezed.shape}")


# x_reshaped

Previous tensortensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previos shapetorch.Size([1, 10])

New tensor:tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

New Shape:torch.Size([10])


In [136]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target:{x_squeezed}")
print(f"previos shape:{x_squeezed.shape}")

#Add an extra dimension with unsqeeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0) # try dim=1
print(f"\nNew tensor:{x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")


Previous target:tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
previos shape:torch.Size([10])

New tensor:tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New Shape: torch.Size([1, 10])


In [137]:
x_reshaped.squeeze()

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [138]:
x_reshaped.squeeze().shape

torch.Size([10])

In [143]:
#torch.permute()- reshapes the dimensions of a target tensor is specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

#permute the original tensor to rearange the axis (or dim) order
x_permuted= x_original.permute(2,0,1) #shifts axis 0->1 ,1->2 2->0

print(f"previos shape:{x_original.shape}")
print(f"New Shape:{x_permuted.shape}") #color_channels, height, width


previos shape:torch.Size([224, 224, 3])
New Shape:torch.Size([3, 224, 224])


In [149]:
x_original[0,0,0]=213
x_original[0,0,0],x_permuted[0,0,0]

(tensor(213.), tensor(213.))

# Indexing (Selecting data from tensors)

Indexing with pytorch is similar to indexing with NumPy

In [154]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [182]:
x[0][2][2]

tensor(9)

In [197]:
x[:,0,:]

tensor([[1, 2, 3]])

In [168]:
x[:,1]

tensor([[4, 5, 6]])

In [171]:
#get all the value of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [172]:
# get all the value of oth dim but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

# Pytorch tensors & NumPy

NumPy is a popular scientific python numerical computing library

And because of this,pytorch has functionality to interact with it.

* Data in NumPy,want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor ->NumPy -> `torch.Tensor.numpy()`

In [199]:
import torch
import numpy as np

array=np.arange(1.0,8.0)

tensor=torch.from_numpy(array) # warning: when converting from numpy-> pytorch,pytorch reflects numpy's default datatype of float64 unless specified
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [200]:
array.dtype

dtype('float64')

In [201]:
tensor.dtype

torch.float64

In [202]:
#but if we create from the tensor
torch.arange(1.0,8.0).dtype

torch.float32

In [205]:
#to change the dtype in numpy
tensor=torch.from_numpy(array).type(torch.float32)
tensor.dtype # compare above this

torch.float32

In [207]:
#change the value of array , what will this do to `tensor`?
array=array+1
array,tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [209]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [210]:
numpy_tensor.dtype

dtype('float32')

In [211]:
# Change the tensor, what happens to `numpy_tensor`?
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibilty (trying to take random out of random)

In short how neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them of data -> again -> again -> again....`

To reduce the randomness in neural networks and pytorch comes the concept of **random seed**

Essentially what the random seed does is "flavour" the randomness

In [212]:
torch.rand(2,2)

tensor([[0.3071, 0.7420],
        [0.0625, 0.4363]])

In [213]:
import torch

In [215]:
#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B= torch.rand(3,4)

In [217]:
1==1

True

In [216]:
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6620, 0.3022, 0.3631, 0.1503],
        [0.3182, 0.6112, 0.4910, 0.0720],
        [0.4782, 0.6727, 0.3686, 0.6731]])
tensor([[0.8672, 0.5273, 0.2964, 0.3664],
        [0.6356, 0.8321, 0.2903, 0.2821],
        [0.2571, 0.1812, 0.2629, 0.7580]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [218]:
# Let's make some random but reproducible tensors

#Set the random seed
RANDOM_SEED=43
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(3,4)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C==random_tensor_D)

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[0.5191, 0.5335, 0.5375, 0.7058],
        [0.4275, 0.2761, 0.8396, 0.1563],
        [0.1072, 0.7261, 0.3241, 0.8892]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
